
[[constraint]]
  branch = "master"
  name = "github.com/HcashOrg/hcd"
  
[[constraint]]
  branch = "master"
  name = "github.com/HcashOrg/hcrpcclient"

[[constraint]]
  branch = "master"
  name = "github.com/HcashOrg/hcd/hcutil"